openapi: 3.0.0
info:
  title: My Micro Certs
  version: '1.0'
servers:
  - url: 'http://localhost:8000/api'
    description: Development
paths:
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  /home:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: get-home
  /plans:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                  first_page_url:
                    type: string
                  from:
                    type: integer
                  last_page:
                    type: integer
                  last_page_url:
                    type: string
                  next_page_url:
                    type: string
                  path:
                    type: string
                  per_page:
                    type: integer
                  prev_page_url:
                    type: string
                  to:
                    type: integer
                  total:
                    type: integer
              examples:
                example-1:
                  value:
                    current_page: 1
                    data:
                      - id: 55397b0b-0b0b-4d4d-9663-b17a75e56514
                        name: Free Subscription
                        description: For developers and small teams
                        currency: USD
                        price: 0
                        credits: 50
                        api_requests_per_hour: 1000
                      - id: d423472f-4671-4e8d-b741-51f0b30a6300
                        name: Plan I
                        description: For small business
                        currency: USD
                        price: 19.9
                        credits: 200
                        api_requests_per_hour: 2500
                      - id: fc06d305-3707-4480-868a-a91174474da1
                        name: Plan II
                        description: For medium business
                        currency: USD
                        price: 29.9
                        credits: 500
                        api_requests_per_hour: 5000
                    first_page_url: 'http://localhost:8000/api/plans?page=1'
                    from: 1
                    last_page: 1
                    last_page_url: 'http://localhost:8000/api/plans?page=1'
                    next_page_url: null
                    path: 'http://localhost:8000/api/plans'
                    per_page: 10
                    prev_page_url: null
                    to: 3
                    total: 3
      operationId: get-plans
components:
  schemas: {}
